---
- name: Run apt-get update
  command: apt-get update

- name: apt install apt-transport-https
  command: sudo apt install apt-transport-https ca-certificates curl gnupg2 software-properties-common -y

- name: Download Docker Key
  command: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  ignore_errors: true

- name: Set Docker Repo
  command: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

- name: Run apt-get update
  command: apt-get update

- name: Set Docker Policy
  command: apt-cache policy docker-ce
  ignore_errors: true

- name: Install Docker
  command: sudo apt install docker-ce -y
  ignore_errors: true

- name: Starting Service
  command: sudo docker run -d -p 8080:8080 shoubhikghosh83/devops:latest
